// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: grpcserver/hexagon.proto

package hexagonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_grpcserver_hexagon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_hexagon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_grpcserver_hexagon_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_grpcserver_hexagon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_hexagon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_grpcserver_hexagon_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_grpcserver_hexagon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_hexagon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_grpcserver_hexagon_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_grpcserver_hexagon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcserver_hexagon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_grpcserver_hexagon_proto_rawDescGZIP(), []int{3}
}

func (x *StreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_grpcserver_hexagon_proto protoreflect.FileDescriptor

const file_grpcserver_hexagon_proto_rawDesc = "" +
	"\n" +
	"\x18grpcserver/hexagon.proto\x12\fhexagon.grpc\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\">\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"?\n" +
	"\rStreamRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"@\n" +
	"\x0eStreamResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index2\xae\x02\n" +
	"\vDemoService\x12>\n" +
	"\x05Unary\x12\x19.hexagon.grpc.EchoRequest\x1a\x1a.hexagon.grpc.EchoResponse\x12K\n" +
	"\fServerStream\x12\x1b.hexagon.grpc.StreamRequest\x1a\x1c.hexagon.grpc.StreamResponse0\x01\x12G\n" +
	"\fClientStream\x12\x19.hexagon.grpc.EchoRequest\x1a\x1a.hexagon.grpc.EchoResponse(\x01\x12I\n" +
	"\n" +
	"BidiStream\x12\x19.hexagon.grpc.EchoRequest\x1a\x1c.hexagon.grpc.StreamResponse(\x010\x01B\x16Z\x14grpcserver/hexagonpbb\x06proto3"

var (
	file_grpcserver_hexagon_proto_rawDescOnce sync.Once
	file_grpcserver_hexagon_proto_rawDescData []byte
)

func file_grpcserver_hexagon_proto_rawDescGZIP() []byte {
	file_grpcserver_hexagon_proto_rawDescOnce.Do(func() {
		file_grpcserver_hexagon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcserver_hexagon_proto_rawDesc), len(file_grpcserver_hexagon_proto_rawDesc)))
	})
	return file_grpcserver_hexagon_proto_rawDescData
}

var file_grpcserver_hexagon_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpcserver_hexagon_proto_goTypes = []any{
	(*EchoRequest)(nil),    // 0: hexagon.grpc.EchoRequest
	(*EchoResponse)(nil),   // 1: hexagon.grpc.EchoResponse
	(*StreamRequest)(nil),  // 2: hexagon.grpc.StreamRequest
	(*StreamResponse)(nil), // 3: hexagon.grpc.StreamResponse
}
var file_grpcserver_hexagon_proto_depIdxs = []int32{
	0, // 0: hexagon.grpc.DemoService.Unary:input_type -> hexagon.grpc.EchoRequest
	2, // 1: hexagon.grpc.DemoService.ServerStream:input_type -> hexagon.grpc.StreamRequest
	0, // 2: hexagon.grpc.DemoService.ClientStream:input_type -> hexagon.grpc.EchoRequest
	0, // 3: hexagon.grpc.DemoService.BidiStream:input_type -> hexagon.grpc.EchoRequest
	1, // 4: hexagon.grpc.DemoService.Unary:output_type -> hexagon.grpc.EchoResponse
	3, // 5: hexagon.grpc.DemoService.ServerStream:output_type -> hexagon.grpc.StreamResponse
	1, // 6: hexagon.grpc.DemoService.ClientStream:output_type -> hexagon.grpc.EchoResponse
	3, // 7: hexagon.grpc.DemoService.BidiStream:output_type -> hexagon.grpc.StreamResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpcserver_hexagon_proto_init() }
func file_grpcserver_hexagon_proto_init() {
	if File_grpcserver_hexagon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcserver_hexagon_proto_rawDesc), len(file_grpcserver_hexagon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcserver_hexagon_proto_goTypes,
		DependencyIndexes: file_grpcserver_hexagon_proto_depIdxs,
		MessageInfos:      file_grpcserver_hexagon_proto_msgTypes,
	}.Build()
	File_grpcserver_hexagon_proto = out.File
	file_grpcserver_hexagon_proto_goTypes = nil
	file_grpcserver_hexagon_proto_depIdxs = nil
}
